controller_list:
  - name: fake_arm_world_left_controller
    joints:
      - kuka_left_joint1
      - kuka_left_joint2
      - kuka_left_joint3
      - kuka_left_joint4
      - kuka_left_joint5
      - kuka_left_joint6
      - kuka_left_joint7
  - name: fake_arm_world_right_controller
    joints:
      - kuka_right_joint1
      - kuka_right_joint2
      - kuka_right_joint3
      - kuka_right_joint4
      - kuka_right_joint5
      - kuka_right_joint6
      - kuka_right_joint7